name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: ['8.0.0', '8.1.0']

    name: PHP 8.1.0, composer platform.php ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@2.21.0
      with:
        php-version: 8.1.0

    - name: Composer config platform.php ${{ matrix.php }}
      run: composer config platform.php ${{ matrix.php }}

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyze --no-progress
